extra_fn_clean_exts:
  - type: regex
    pattern: "_R[12].*"
  - "_htseq.genes.tsv"

use_filename_as_sample_name:
  - cutadapt

custom_data:
  biotypes_counts:
    file_format: "tsv"
    section_name: "Biotype Summary"
    description: "Number of reads aligned to genes of given biotype class"
    plot_type: "bargraph"
    pconfig:
      id: "biotypes_barplot"
      title: "Biotype Summary"
      xlab: "Sample"
      ylab: "Read count"
      logswitch: True
      orientation: "horizontal"
      #sort: "descending"
sp:
  biotypes_counts:
    fn: "*.biotypes.tsv"
    delimiter: "\t"
    sample_column: 1
    data_column: 2
